

#系统函数帮助说明，各分类按字母序排列
_all_func_ = {
                
    'K线数据': [
                    ['BarCount'            , 'Bar总数'],
                    ['BarStatus'           , '当前Bar状态值'],
                    ['Close'               , '收盘价,简写C'],
                    ['CurrentBar'          , '当前Bar索引值'],
                    ['Date'                , '当前Bar日期,简写D'],
                    ['High'                , '最高价,简写H'],
                    ['HistoryDataExist'    , '历史数据是否存在'],
                    ['Low'                 , '最低价,简写L'],
                    ['Open'                , '开盘价,简写O'],
                    ['OpenInt'             , '持仓量'],
                    ['Time'                , '当前Bar时间,简写T'],
                    ['TradeDate'           , '当前Bar的交易日'],
                    ['Vol'                 , '成交量,简写V'], 
                ],
                
    '即时行情': [
                    ['Q_AskPrice'          , '最新卖价'],
                    ['Q_AskPriceFlag'      , '卖价变化标志'],
                    ['Q_AskVol'            , '最新卖量'],
                    ['Q_AvgPrice'          , '实时均价'],
                    ['Q_BidPrice'          , '最新买价'],
                    ['Q_BidPriceFlag'      , '买价变化标志'],
                    ['Q_BidVol'            , '最新买量'],
                    ['Q_Close'             , '当日收盘价'],
                    ['Q_High'              , '当日最高价'],
                    ['Q_HisHigh'           , '历史最高价'],
                    ['Q_HisLow'            , '历史最低价'],
                    ['Q_InsideVol'         , '内盘'],
                    ['Q_Last'              , '最新价'],
                    ['Q_LastDate'          , '最新成交日期'],
                    ['Q_LastFlag'          , '最新价变化标志'],
                    ['Q_LastTime'          , '最新成交时间'],
                    ['Q_LastVol'           , '现手'],
                    ['Q_Low'               , '当日最低价'],
                    ['Q_LowLimit'          , '当日跌停价'],
                    ['Q_Open'              , '当日开盘价'],
                    ['Q_OpenInt'           , '持仓量'],
                    ['Q_OpenIntFlag'       , '持仓变化标志'],
                    ['Q_OutsideVol'        , '外盘量'],
                    ['Q_PreOpenInt'        , '昨持仓'],
                    ['Q_PreSettlePrice'    , '昨结算'],
                    ['Q_PriceChg'          , '当日涨跌'],
                    ['Q_PriceChgRadio'     , '当日涨跌幅'],
                    ['Q_TodayEntryVol'     , '当日开仓量'],
                    ['Q_TodayExitVol'      , '当日平仓量'],
                    ['Q_TotalVol'          , '当日成交量'],
                    ['Q_TurnOver'          , '当日成交金额'],
                    ['Q_UpperLimit'        , '当日涨停价'],
                    ['QuoteDataExist'      , '行情数据是否有效'],
                ],
                
    '策略交易': [
                    ['Buy'                 , '多头建仓'],
                    ['BuyToCover'          , '空头平仓'],
                    ['Sell'                , '多头平仓'],
                    ['SellShort'           , '空头建仓']
                ],
                
    '属性函数': [
                    ['BarInterval'         , '图表周期数值'],
                    ['BarType'             , '图表周期类型'],
                    ['BidAskSize'          , '买卖盘个数'],
                    ['BigPointValue'       , '每点价值'],
                    # ['CanTrade'            , '是否支持交易'],
                    ['ContractUnit'        , '每手乘数'],
                    ['ExchangeName'        , '交易所名称'],
                    # ['ExpiredDate'         , '最后交易日'],
                    ['GetSessionCount'     , '交易时段个数'],
                    ['GetSessionEndTime'   , '交易时段结束时间'],
                    ['GetSessionStartTime' , '交易时段起始时间'],
                    ['MarginRatio'         , '保证金比例'],
                    ['MaxBarsBack'         , '最大回溯Bar数'],
                    ['MaxSingleTradeSize'  , '单笔交易限量'],
                    ['MinMove'             , '最小变动量'],
                    ['OptionStyle'         , '期权类型'],
                    ['OptionType'          , '看涨看跌'],
                    ['PriceScale'          , '价格精度'],
                    ['RelativeSymbol'      , '关联合约'],
                    ['StrikePrice'         , '期权行权价'],
                    ['Symbol'              , '合约编号'],
                    ['SymbolName'          , '合约名称'],
                    ['SymbolType'          , '品种编号'],
                ],
                
    '策略状态': [
                    ['AvgEntryPrice'       , '当前持仓平均建仓价格'],
                    ['BarsSinceEntry'      , '当前持仓的第一个建仓位置到当前位置的Bar计数'],
                    ['BarsSinceExit'       , '最近平仓位置到当前位置的Bar计数'],
                    ['BarsSinceLastEntry'  , '当前持仓的最后一个建仓位置到当前位置的Bar计数'],
                    ['ContractProfit'      , '当前持仓位置的每手浮动盈亏'],
                    ['CurrentContracts'    , '当前持仓的持仓合约数'],
                    ['CurrentEntries'      , '当前持仓的建仓次数'],
                    ['EntryDate'           , '当前持仓的第一个建仓位置的日期'],
                    ['EntryPrice'          , '当前持仓的第一个建仓价格'],
                    ['EntryTime'           , '当前持仓的第一个建仓位置的时间'],
                    ['ExitDate'            , '最近平仓位置Bar日期'],
                    ['ExitPrice'           , '最近平仓位置的平仓价格'],
                    ['ExitTime'            , '最近平仓位置Bar时间'],
                    ['LastEntryDate'       , '当前持仓的最后一个建仓位置的日期'],
                    ['LastEntryPrice'      , '当前持仓的最后一个建仓价格'],
                    ['LastEntryTime'       , '当前持仓的最后一个建仓位置的时间'],
                    ['MarketPosition'      , '当前持仓状态'],
                    ['MaxContracts'        , '当前持仓的最大持仓合约数'],
                    ['MaxEntries'          , '最大的建仓次数'],
                    ['MaxPositionLoss'     , '当前持仓的最大浮动亏损数'],
                    ['MaxPositionProfit'   , '当前持仓的最大浮动盈利数'],
                    ['PositionProfit'      , '当前持仓位置的浮动盈亏'],
                ],
                
                
    '策略性能': [
                    ['Available'           , '策略当前可用虚拟资金'],
                    ['FloatProfit'         , '浮动盈亏'],
                    ['GrossLoss'           , '累计总亏损'],
                    ['GrossProfit'         , '累计总利润'],
                    ['Margin'              , '持仓保证金'],
                    ['NetProfit'           , '平仓盈亏'],
                    ['NumEvenTrades'       , '保本交易总手数'],
                    ['NumLosTrades'        , '亏损交易总手数'],
                    ['NumWinTrades'        , '盈利交易总手数'],
                    ['NumAllTimes'         , '开仓次数'],
                    ['NumWinTimes'         , '盈利次数'],
                    ['NumLoseTimes'        , '亏损次数'],
                    ['NumEventTimes'       , '保本次数'],
                    ['PercentProfit'       , '盈利成功率'],
                    ['TradeCost'           , '交易产生的手续费'],
                    ['TotalTrades'         , '交易总开仓手数'],
                ],
                
    '账户函数': [
                    ['A_AccountID'         , '交易账户ID'],
                    ['A_Cost'              , '手续费'],
                    ['A_CurrentEquity'     , '账户权益'],
                    ['A_FreeMargin'        , '可用资金'],
                    ['A_ProfitLoss'        , '浮动盈亏'],
                    ['A_TotalFreeze'       , '冻结资金'],
                    ['A_BuyAvgPrice'       , '买入均价'],
                    ['A_BuyPosition'       , '买持仓量'],
                    ['A_BuyProfitLoss'     , '买浮动盈亏'],
                    ['A_SellAvgPrice'      , '卖出均价'],
                    ['A_SellPosition'      , '卖持仓量'],
                    ['A_SellProfitLoss'    , '卖浮动盈亏'],
                    ['A_TotalAvgPrice'     , '总持仓均价'],
                    ['A_TotalPosition'     , '总持仓量'],
                    ['A_TotalProfitLoss'   , '总浮动盈亏'],
                    ['A_TodayBuyPosition'  , '当日买持仓'],
                    ['A_TodaySellPosition' , '当日卖持仓'],
                    ['A_OrderBuyOrSell'    , '买卖方向'],
                    ['A_OrderEntryOrExit'  , '开平标识'],
                    ['A_OrderFilledLot'    , '定单成交数量'],
                    ['A_OrderFilledPrice'  , '定单成交价格'],
                    ['A_OrderLot'          , '委托数量'],
                    ['A_OrderPrice'        , '委托价格'],
                    ['A_OrderStatus'       , '定单状态'],
                    ['A_OrderTime'         , '下单时间'],
                    ['A_SendOrder'         , '下单'],
                    ['A_DeleteOrder'       , '撤单']
                ],
                
    '枚举函数': [
                    ['Enum_Buy'            , '买卖类型_买入'],
                    ['Enum_Sell'           , '买卖类型_卖出'],
                    ['Enum_Entry'          , '开平类型_开仓'], 
                    ['Enum_Exit'           , '开平类型_平仓'],
                    ['Enum_ExitToday'      , '开平类型_平今'],
                    ['Enum_EntryExitIgnore', '开平类型_不区分开平'],
                    ['Enum_Sended'         , '已发送'],
                    ['Enum_Accept'         , '已受理'],
                    ['Enum_Triggering'     , '待触发'],
                    ['Enum_Active'         , '已生效'],
                    ['Enum_Queued'         , '已排队'],   
                    ['Enum_FillPart'       , '部分成交'],
                    ['Enum_Filled'         , '完全成交'],
                    ['Enum_Canceling'      , '待撤'],
                    ['Enum_Modifying'      , '待改'],
                    ['Enum_Canceled'       , '已撤单'],
                    ['Enum_PartCanceled'   , '已撤余单'],
                    ['Enum_Fail'           , '指令失败'],
                    ['Enum_Suspended'      , '已挂起'],
                    ['Enum_Apply'          , '已申请'],
                    ['Enum_Period_Tick'    , '周期类型_分笔'],
                    ['Enum_Period_Dyna'    , '周期类型_分时'],
                    ['Enum_Period_Second'  , '周期类型_秒线'],
                    ['Enum_Period_Min'     , '周期类型_分钟'],
                    ['Enum_Period_Hour'    , '周期类型_小时'],
                    ['Enum_Period_Day'     , '周期类型_日线'],
                    ['Enum_Period_Week'    , '周期类型_周线'],
                    ['Enum_Period_Month'   , '周期类型_月线'],
                    ['Enum_Period_Year'    , '周期类型_年线'],
                    ['Enum_Period_DayX'    , '周期类型_多日'],
                ],
                
    '绘图函数': [
                    ['PlotNumeric'         , '绘制指标线'],
                ],

    '设置函数': [
                    ['GetConfig'           , '获取设置参数'],
                    ['SetBenchmark'        , '设置基准合约'],
                    ['SetUserNo'           , '设置交易账号'],
                    ['SetAllKTrue'         , '使用所有K线回测'],
                    ['SetBarInterval'      , '设置K线类型'],
                    ['SetBarPeriod'        , '设置起始时间'],
                    ['SetBarCount'         , '设置K线数量'],
                    ['SetInitCapital'      , '设置初始资金'],
                    ['SetMargin'           , '设置保证金'],
                    ['SetTradeFee'         , '设置手续费'],
                    ['SetTradeMode'        , '设置运行方式']
                ],
}
